"""empty message

Revision ID: 1512d2c87161
Revises: fd3d680a76ba
Create Date: 2022-01-31 11:17:54.566809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1512d2c87161'
down_revision = 'fd3d680a76ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruladdcomp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ruladdcomp')
    # ### end Alembic commands ###
