"""empty message

Revision ID: 1e22125c97c4
Revises: 1080d050460c
Create Date: 2022-01-26 15:23:29.319394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e22125c97c4'
down_revision = '1080d050460c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('introtext', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('tit', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('key', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('des', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'des')
    op.drop_column('post', 'key')
    op.drop_column('post', 'tit')
    op.drop_column('post', 'introtext')
    # ### end Alembic commands ###
