"""empty message

Revision ID: 4dea65feaa21
Revises: 0b5dccaf39b6
Create Date: 2022-02-08 18:48:35.120395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dea65feaa21'
down_revision = '0b5dccaf39b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divorced')
    op.drop_table('company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=160), nullable=True),
    sa.Column('image', sa.VARCHAR(length=100), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
    sa.Column('divorced_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['divorced_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('divorced',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=160), nullable=True),
    sa.Column('image', sa.VARCHAR(length=100), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
