"""empty message

Revision ID: 50ddf5acab46
Revises: e5cc62b750af
Create Date: 2022-02-22 16:00:46.746744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ddf5acab46'
down_revision = 'e5cc62b750af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('stars_comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars_comments', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
