"""empty message

Revision ID: 621527a50df5
Revises: 16584aef1282
Create Date: 2022-02-22 15:55:25.909797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621527a50df5'
down_revision = '16584aef1282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars_comments', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('stars_comments')

    # ### end Alembic commands ###
