"""empty message

Revision ID: be3cab279836
Revises: 50ddf5acab46
Create Date: 2022-02-22 17:34:37.274230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3cab279836'
down_revision = '50ddf5acab46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('publish')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
