"""empty message

Revision ID: be4d3c523539
Revises: 4c6e126c24d5
Create Date: 2022-02-16 23:21:18.342365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4d3c523539'
down_revision = '4c6e126c24d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('publish', sa.Boolean(), nullable=False))
    op.add_column('comments', sa.Column('datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'datetime')
    op.drop_column('comments', 'publish')
    # ### end Alembic commands ###
