"""empty message

Revision ID: ea9896fe3451
Revises: 39125d5cb86c
Create Date: 2022-02-10 16:09:58.666493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9896fe3451'
down_revision = '39125d5cb86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('stars', sa.String(length=140), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stars')
    )
    op.add_column('company', sa.Column('href', sa.String(length=100), nullable=True))
    op.add_column('company', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('company', sa.Column('map', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'map')
    op.drop_column('company', 'content')
    op.drop_column('company', 'href')
    op.drop_table('comments')
    # ### end Alembic commands ###
