"""empty message

Revision ID: f151103d50e1
Revises: 621527a50df5
Create Date: 2022-02-22 15:59:55.831767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f151103d50e1'
down_revision = '621527a50df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('stars')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
